name: basic-sonar-scann
on:
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Init Pipeline
        run: |
          echo "Init pipeline to Test Sonar"
          sleep 5
          
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.POC_SONAR_TOKEN }}