name: parallel-security-scans-v2

on:
  workflow_dispatch:

jobs:
    sonar:
      name: SonarQube Cloud Scan
      runs-on: ubuntu-latest
      
      outputs:
        scan_status: ${{ steps.sonar_outputs.outputs.scan_status }}
        quality_gate: ${{ steps.sonar_outputs.outputs.quality_gate }}
        artifact_name: sonar-reports


      steps:  
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          
      - name: Run SonarQube scan
        id: sonar_scan
        continue-on-error: true
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.POC_SONAR_TOKEN }}
          
      - name: Create Sonar report directory
        if: always()
        run: mkdir -p reports/sonar

      - name: Verify current workspace
        run: |
          cat /etc/os-release
          pwd
          ls -la

      - name: Preserve Sonar task metadata
        if: always()
        run: |
          if [ -f .scannerwork/report-task.txt ]; then
            echo "inside .scannerwork"
            cp .scannerwork/report-task.txt reports/sonar/report-task.txt
            echo "report-task.txt is "
            cat reports/sonar/report-task.txt
          fi

      - name: Obtain Sonar quality gate
        id: sonar_api
        if: always()
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.POC_SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ vars.POC_SONAR_PROJECT_JUICE_SHOP_KEY }}
        run: |
          curl --silent \
            --show-error \
            --fail-with-body \
            --header "Authorization: Bearer ${SONAR_TOKEN}" \
            --get \
            --data-urlencode "projectKey=${SONAR_PROJECT_KEY}" \
            "https://sonarcloud.io/api/qualitygates/project_status" \
            --output reports/sonar/quality-gate.json
            
          echo "#######################################################"
          cat ./reports/sonar/quality-gate.json | jq
          echo "#######################################################"

      - name: Obtain first page of Sonar Issues
        if: always()
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.POC_SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ vars.POC_SONAR_PROJECT_JUICE_SHOP_KEY }}
        run: |
          curl --silent \
            --show-error \
            --fail-with-body \
            --header "Authorization: Bearer ${SONAR_TOKEN}" \
            --get \
            --data-urlencode "componentKeys=${SONAR_PROJECT_KEY}" \
            --data-urlencode "ps=500" \
            "https://sonarcloud.io/api/issues/search" \
            --output reports/sonar/issues-page-1.json  

      - name: Create Sonar outputs
        id: sonar_output  
        if: always()
        env:
          SCAN_STATUS: ${{ steps.sonar_scan.outcome }} 
        run: |
          quality_gate="UNKNOWN"
          
          if [ -f reports/sonar/quality-gate.json ]; then
            quality_gate="$(
              jq -r '.projectStatus.status // "UNKNOWN"' \
                reports/sonar/quality-gate.json 
            )"
          fi

          echo "scan_status=${SCAN_STATUS}" >> "$GITHUB_OUTPUT"
          echo "quality_gate=${quality_gate}" >> "$GITHUB_OUTPUT"

          {
            echo "## SonarQube"
            echo "- Scan: ${SCAN_STATUS}"
            echo "- Quality Gate: ${quality_gate}"
          } >> "$GITHUB_STEP_SUMMARY"

      
      #- name: Upload Sonar reports
      #  i f: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: sonar-reports
      #    path: reports/sonar
      #    if-no-files-found: warn
      #    retention-days: 15

    snyk:
      name: Snyk Open Source Scan
      runs-on: ubuntu-latest    

      steps:  
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          
      - name: Configure Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          package-manager-cache: false

      - name: Install project dependencies
        run: npm install --ignore-scripts

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        
      - name: Create Snyk report directory
        run: mkdir -p reports/snyk
        
      - name: Run Snyk Open Source scan
        id: snyk_scan
        env:
          SNYK_TOKEN: ${{ secrets.POC_SNYK_TOKEN }}
        run: |
          set +e
          
          snyk test \
            --file=package.json \
            --package-manager=npm \
            --json-file-output=reports/snyk/snyk-results.json \
            --sarif-file-output=reports/snyk/snyk-results/sarif

          exit_code=$?
          set -e

      - name: Publish snapshot to Snyk Portal
        if: github.ref == 'refs/heads/main'
        env:
          SNYK_TOKEN: ${{ secrets.POC_SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.POC_SNYK_ORG_ID }} 
        run: |
          snyk monitor \
            --file=package.json \
            --package-manager=npm \
            --org="$SNYK_ORG_ID" \
            --project-name="${{ github.repository }}" \
            --target-reference="${{ github.ref_name }}" \
            --remote-repo-url="${{ github.server_url }}/${{ github.repository }}" 