name: parallel-security-scans-v2

on:
  workflow_dispatch:

jobs:
    sonar:
      name: SonarQube Cloud Scan
      runs-on: ubuntu-latest    

      steps:  
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          
      - name: Run SonarQube scan
        id: sonar_scan
        continue-on-error: true
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.POC_SONAR_TOKEN }}    

    snyk:
      name: Snyk Open Source Scan
      runs-on: ubuntu-latest    

      steps:  
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0    